# Generated by Django 4.1.5 on 2023-02-08 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trainnum', models.PositiveIntegerField()),
                ('origincity', models.CharField(max_length=260)),
                ('destinationcity', models.CharField(max_length=260)),
                ('TrainFare', models.PositiveIntegerField()),
            ],
        ),
    ]
